language: generic
dist: trusty
sudo: false

branches:
  only:
    - master

env:
  global:
    - GH_REPO_REF: github.com/bigclownlabs/bc-core-module-sdk.git
    - GH_REPO_NAME: bc-core-module-sdk
    - GH_PAGES_BRANCH: gh-pages
    - GH_PAGES_CNAME: api.bigclown.com
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - HTML_DIR: $TRAVIS_BUILD_DIR/doc/html

addons:
  apt:
    packages:
      - doxygen
      - graphviz

script:
  - /bin/sh deploy-doc.sh
